# Generated by Django 4.1.2 on 2022-11-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comments_date_project_category_project_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
