# Generated by Django 4.1.2 on 2022-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_typeofapp_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
